# Generated by Django 2.2.7 on 2019-12-28 10:13

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191119_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='上次更新时间')),
                ('QQ', models.CharField(max_length=20, verbose_name='QQ')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('about_content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='关于博主')),
            ],
        ),
    ]
