# Generated by Django 2.2.7 on 2019-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '关于博主', 'verbose_name_plural': '关于博主'},
        ),
        migrations.AddField(
            model_name='about',
            name='weixin',
            field=models.ImageField(blank=True, null=True, upload_to='weixin_squarecode/', verbose_name='微信二维码'),
        ),
    ]
