# Generated by Django 2.2.7 on 2020-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191228_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=200, verbose_name='座右铭')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='头像')),
            ],
            options={
                'verbose_name_plural': '头像',
                'verbose_name': '头像',
            },
        ),
    ]
